// 데이타이전 엑셀 템플릿
export const MigrationTemplate = [
  {
    type: '생산처',
    typeCd: 'A',
    column: [
      { header: '생산처', width: 20, required: true, comment: '* 필수' },
      { header: '휴면', width: 20, required: false, comment: '선택' },
      { header: '구분1', width: 20, required: false, comment: '선택' },
      { header: '구분2', width: 20, required: false, comment: '선택' },
      { header: '현잔액', width: 20, required: true, comment: '* 필수 (숫자)' },
      { header: '잔액인쇄', width: 30, required: false, comment: '선택 (True/False)' },
      { header: '처리확인', width: 30, required: false, comment: '선택 (True/False)' },
      { header: '등록일자', width: 40, required: true, comment: '* 필수 (YYYY-MM-DD)' },
      { header: '대표자', width: 20, required: false, comment: '선택' },
      { header: '담당자', width: 20, required: false, comment: '선택' },
      { header: '대표자HP', width: 20, required: false, comment: '선택' },
      { header: '담당자HP', width: 20, required: false, comment: '선택' },
      { header: '전화', width: 20, required: false, comment: '선택' },
      { header: '팩스', width: 20, required: false, comment: '선택' },
      { header: '주소', width: 20, required: false, comment: '선택' },
      { header: '비고(화면)', width: 20, required: false, comment: '선택' },
      { header: '비고(전표)', width: 20, required: false, comment: '선택' },
    ],
  },
  {
    type: '판매처',
    typeCd: 'B',
    column: [
      { header: '판매처', width: 20, required: true, comment: '* 필수' },
      { header: '휴면', width: 20, required: true, comment: '* 필수 (True/False)' },
      { header: '구분1', width: 20, required: false, comment: '선택' },
      { header: '구분2', width: 20, required: false, comment: '선택' },
      { header: '현잔액', width: 20, required: true, comment: '* 필수 (숫자)' },
      { header: '잔액상한', width: 20, required: false, comment: '선택 (숫자)' },
      { header: '혼용률', width: 30, required: false, comment: '선택 (True/False)' },
      { header: '잔액인쇄', width: 30, required: false, comment: '선택 (True/False)' },
      { header: '처리확인', width: 40, required: true, comment: '선택 (True/False)' },
      { header: '계산서', width: 20, required: false, comment: '선택 (True/False)' },
      { header: '부가세', width: 20, required: false, comment: '선택 (True/False)' },
      { header: '등록일자', width: 20, required: true, comment: '* 필수 (YYYY-MM-DD)' },
      { header: '대표자', width: 20, required: false, comment: '선택' },
      { header: '담당자', width: 20, required: false, comment: '선택' },
      { header: '대표자HP', width: 20, required: false, comment: '선택' },
      { header: '담당자HP', width: 20, required: false, comment: '선택' },
      { header: '전화', width: 20, required: false, comment: '선택' },
      { header: '팩스', width: 20, required: false, comment: '선택' },
      { header: '주소', width: 20, required: false, comment: '선택' },
      { header: '사업자상호', width: 20, required: false, comment: '선택' },
      { header: '사업자번호', width: 20, required: false, comment: '선택' },
      { header: '사업장주소', width: 20, required: false, comment: '선택' },
      { header: '업태', width: 20, required: false, comment: '선택' },
      { header: '종목', width: 20, required: false, comment: '선택' },
      { header: '전자계산서eMail', width: 20, required: false, comment: '선택' },
      { header: '비고(화면)', width: 20, required: false, comment: '선택' },
      { header: '비고(전표)', width: 20, required: false, comment: '선택' },
      { header: '계좌(전표)', width: 20, required: false, comment: '선택' },
      { header: '매입잔액', width: 20, required: false, comment: '선택(숫자)' },
    ],
  },
  {
    type: '상품',
    typeCd: 'C',
    column: [
      { header: '품명', width: 20, required: true, comment: '* 필수' },
      { header: '칼라', width: 20, required: true, comment: '* 필수' },
      { header: '사이즈', width: 20, required: true, comment: '* 필수' },
      { header: '휴면', width: 20, required: true, comment: '* 필수 (True/False)' },
      { header: '공장', width: 20, required: false, comment: '선택' },
      { header: '디자이너', width: 20, required: false, comment: '선택' },
      { header: '거래처', width: 20, required: false, comment: '선택' },
      { header: '입고가', width: 20, required: false, comment: '선택 (숫자)' },
      { header: '제품원가', width: 20, required: true, comment: '* 필수 (숫자)' },
      { header: '도매가', width: 20, required: true, comment: '* 필수 (숫자)' },
      { header: '소매가', width: 20, required: false, comment: '선택 (숫자)' },
      { header: '혼용률', width: 20, required: false, comment: '선택' },
      { header: '등록일자', width: 20, required: false, comment: '선택' },
      { header: '비고', width: 20, required: false, comment: '선택' },
      { header: '외부바코드', width: 20, required: false, comment: '선택' },
      { header: '내부바코드', width: 20, required: false, comment: '선택' },
      { header: '계절', width: 20, required: false, comment: '선택' },
      { header: '최소발주숫자', width: 20, required: false, comment: '선택 (숫자)' },
      { header: '요척', width: 20, required: false, comment: '선택' },
      { header: '재고수량', width: 20, required: false, comment: '선택 (숫자)' },
    ],
  },
  {
    type: '미송',
    typeCd: 'D',
    column: [
      { header: '미송일자', width: 20, required: true, comment: '* 필수 (YYYY-MM-DD)' },
      { header: '판매처', width: 20, required: true, comment: '* 필수' },
      { header: '전표#', width: 20, required: false, comment: '선택' },
      { header: '품번', width: 20, required: false, comment: '선택' },
      { header: '품명', width: 20, required: true, comment: '* 필수' },
      { header: '칼라', width: 20, required: true, comment: '* 필수' },
      { header: '사이즈', width: 20, required: true, comment: '* 필수' },
      { header: '거래단가', width: 20, required: true, comment: '* 필수 (숫자)' },
      { header: '완료', width: 20, required: false, comment: '선택 (True/False)' },
      { header: '미송', width: 20, required: false, comment: '선택 (숫자)' },
      { header: '발송', width: 20, required: false, comment: '선택 (숫자)' },
      { header: '잔량', width: 20, required: true, comment: '* 필수 (숫자)' },
      { header: '잔량금액', width: 20, required: true, comment: '* 필수 (숫자)' },
      { header: '비고', width: 20, required: false, comment: '선택' },
    ],
  },
  {
    type: '샘플미회수',
    typeCd: 'F',
    column: [
      { header: '샘플일자', width: 20, required: true, comment: '* 필수 (YYYY-MM-DD)' },
      { header: '판매처', width: 20, required: true, comment: '* 필수' },
      { header: '전표#', width: 20, required: false, comment: '선택' },
      { header: '품번', width: 20, required: false, comment: '선택' },
      { header: '품명', width: 20, required: true, comment: '* 필수' },
      { header: '칼라', width: 20, required: true, comment: '* 필수' },
      { header: '사이즈', width: 20, required: true, comment: '* 필수' },
      { header: '거래단가', width: 20, required: true, comment: '* 필수 (숫자)' },
      { header: '완료', width: 20, required: false, comment: '선택 (True/False)' },
      { header: '샘플', width: 20, required: false, comment: '선택 (숫자)' },
      { header: '회수', width: 20, required: false, comment: '선택 (숫자)' },
      { header: '잔량', width: 20, required: true, comment: '* 필수 (숫자)' },
      { header: '잔량금액', width: 20, required: true, comment: '* 필수 (숫자)' },
      { header: '비고', width: 20, required: false, comment: '선택' },
    ],
  },
  {
    type: '판매원장',
    typeCd: 'G',
    column: [
      { header: '거래일자', width: 20, required: true, comment: '* 필수 (YYYY-MM-DD)' },
      { header: '판매처', width: 20, required: true, comment: '* 필수' },
      { header: '전표#', width: 20, required: false, comment: '선택' },
      { header: '구분', width: 20, required: false, comment: '선택 (판매/반품)' },
      { header: '품번', width: 20, required: false, comment: '선택' },
      { header: '품명', width: 20, required: true, comment: '* 필수' },
      { header: '칼라', width: 20, required: true, comment: '* 필수' },
      { header: '사이즈', width: 20, required: true, comment: '* 필수' },
      { header: '사용자', width: 20, required: false, comment: '선택' },
      { header: '입고가', width: 20, required: false, comment: '선택 (숫자)' },
      { header: '거래단가', width: 20, required: false, comment: '선택 (숫자)' },
      { header: '단가DC', width: 20, required: false, comment: '선택 (숫자)' },
      { header: '판매량', width: 20, required: true, comment: '* 필수 (숫자)' },
      { header: '판매금액', width: 20, required: true, comment: '* 필수 (숫자)' },
      { header: '반품량', width: 20, required: true, comment: '* 필수 (숫자)' },
      { header: '반품금액', width: 20, required: true, comment: '* 필수 (숫자)' },
    ],
  },
  {
    type: '샘플회수',
    typeCd: 'H',
    column: [
      { header: '샘플일자', width: 20, required: true, comment: '* 필수 (YYYY-MM-DD)' },
      { header: '판매처', width: 20, required: true, comment: '* 필수' },
      { header: '전표#', width: 20, required: false, comment: '선택' },
      { header: '품번', width: 20, required: false, comment: '선택' },
      { header: '품명', width: 20, required: true, comment: '* 필수' },
      { header: '칼라', width: 20, required: true, comment: '* 필수' },
      { header: '사이즈', width: 20, required: true, comment: '* 필수' },
      { header: '거래단가', width: 20, required: false, comment: '선택 (숫자)' },
      { header: '완료', width: 20, required: false, comment: '* 필수 (True/False)' },
      { header: '샘플', width: 20, required: false, comment: '* 필수 (숫자)' },
      { header: '회수', width: 20, required: true, comment: '* 필수 (숫자)' },
      { header: '잔량', width: 20, required: true, comment: '* 필수 (숫자)' },
      { header: '잔량금액', width: 20, required: true, comment: '선택 (숫자)' },
      { header: '비고', width: 20, required: true, comment: '선택' },
    ],
  },
  {
    type: '미송발송',
    typeCd: 'I',
    column: [
      { header: '미송일자', width: 20, required: true, comment: '* 필수 (YYYY-MM-DD)' },
      { header: '판매처', width: 20, required: true, comment: '* 필수' },
      { header: '전표#', width: 20, required: false, comment: '선택' },
      { header: '품번', width: 20, required: false, comment: '선택' },
      { header: '품명', width: 20, required: true, comment: '* 필수' },
      { header: '칼라', width: 20, required: true, comment: '* 필수' },
      { header: '사이즈', width: 20, required: true, comment: '* 필수' },
      { header: '거래단가', width: 20, required: false, comment: '선택 (숫자)' },
      { header: '완료', width: 20, required: false, comment: '* 필수 (True/False)' },
      { header: '미송', width: 20, required: false, comment: '* 필수 (숫자)' },
      { header: '발송', width: 20, required: true, comment: '* 필수 (숫자)' },
      { header: '잔량', width: 20, required: true, comment: '* 필수 (숫자)' },
      { header: '잔량금액', width: 20, required: true, comment: '선택 (숫자)' },
      { header: '비고', width: 20, required: true, comment: '선택' },
    ],
  },
  {
    type: '입고원장',
    typeCd: 'J',
    column: [
      { header: '거래일자', width: 20, required: true, comment: '* 필수 (YYYY-MM-DD)' },
      { header: '입고처', width: 20, required: true, comment: '* 필수' },
      { header: '전표#', width: 20, required: false, comment: '선택' },
      { header: '구분', width: 20, required: false, comment: '선택 (입고/반출)' },
      { header: '품번', width: 20, required: false, comment: '선택' },
      { header: '품명', width: 20, required: true, comment: '* 필수' },
      { header: '칼라', width: 20, required: true, comment: '* 필수' },
      { header: '사이즈', width: 20, required: true, comment: '* 필수' },
      { header: '거래단가', width: 20, required: false, comment: '선택 (숫자)' },
      { header: '단가DC', width: 20, required: false, comment: '선택 (숫자)' },
      { header: '입고량', width: 20, required: true, comment: '* 필수 (숫자)' },
      { header: '입고금액', width: 20, required: true, comment: '* 필수 (숫자)' },
      { header: '반출량', width: 20, required: true, comment: '* 필수 (숫자)' },
      { header: '반출금액', width: 20, required: true, comment: '* 필수 (숫자)' },
    ],
  },
  {
    type: '부가세미입금',
    typeCd: 'K',
    column: [
      { header: '청구일자', width: 20, required: true, comment: '* 필수 (YYYY-MM-DD)' },
      { header: '판매처', width: 20, required: true, comment: '* 필수' },
      { header: '대상기간 부터', width: 20, required: false, comment: '선택 (YYYY-MM-DD)' },
      { header: '대상기간 까지', width: 20, required: false, comment: '선택 (YYYY-MM-DD)' },
      { header: '전표#', width: 20, required: false, comment: '선택' },
      { header: '발행', width: 20, required: true, comment: '* 필수 (True/False)' },
      { header: '완료', width: 20, required: true, comment: '선택 (True/False)' },
      { header: '청구금액', width: 20, required: true, comment: '* 필수 (숫자)' },
      { header: '현금입금', width: 20, required: false, comment: '선택 (숫자)' },
      { header: '통장입금', width: 20, required: false, comment: '선택 (숫자)' },
      { header: '할인금액', width: 20, required: true, comment: '선택 (숫자)' },
      { header: '잔액', width: 20, required: true, comment: '* 필수 (숫자)' },
      { header: '비고', width: 20, required: true, comment: '선택' },
    ],
  },
];
